version: "3.8"
services:
  app:
    build: .
    image: cryptransfer
    container_name: cryptransfer
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
