version: "3"
services:
  webapp:
    build: ./webapp
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app:delegated
      - ./webapp/node_modules:/app/node_modules
  python-api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /app/uploads
    depends_on:
      - webapp
  database:
    build: ./database
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
